name = "t-king-pushdeer-notifier-v"
main = "workers/wecom-notifier.ts"
compatibility_date = "2026-05-29"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "t-king-db"
database_id = "5e250ca6-2ee9-4068-b874-8385fa3cd040"

[triggers]
crons = ["*/3 1-7 * * 1-5"]
